spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tdd_db
    username: db_user
    password: db_password
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  sql:
    show: true


